# See travis-ci.org
language: python
python:
    - "2.7"
install:
    - pip install flake8
    - pip install isort
    - pip install autopep8
script:
    - flake8
    - autopep8 -d -aar . --exclude settings.py --ignore E26
    - isort -c -df -rc .
